### ISSUE TITLE
Throws an exception on missing api key, outputs nothing after key is set.

### ISSUE THREAD

**Issue by ShuffleBit** [OpenVoiceOS/skill-ovos-fallback-chatgpt#7]
I'm ovos-newbish. I was going to roll my own gpt skill then found this one. I think it's expecting core functionality that hasn't been committed.

Running on rpi4b, raspbian-ovos-dev image (w/o a TV connected to it) from April.

The skill loads, and throws an exception because the key isn't set. Expected that.

My settings.json is simple:
```
{
    "key": "sk-xxxxxxxxx"
}
```

The skill now loads silently indicating all is well but it remains silent forever with a fallthrough to the "Unknown" response.

The cause of the fallthrough is found in daemon.log: This skill imports the Persona libraries which throw:

`ModuleNotFoundError: No module named 'ovos_plugin_manager.templates.solvers'`

Upgrading ovos-plugin-manager doesn't eliminate the exception, but maybe I did that incorrectly?

I'm gonna roll my own gpt skill since the Persona stuff seems too elegant and fragile for my tastes. Establishing gpt personality is straight forward, and well documented, but I think it's too ephemeral/nuanced and fluid to constrain within a templated structure for now e.g., the number of "jailbreak" tricks being found.

I thought this should be reported because this will be a VERY popular skill on systems where it works.

**Comment by JarbasAl** [comment]
> I'm ovos-newbish. I was going to roll my own gpt skill then found this one. I think it's expecting core functionality that hasn't been committed.
> 
> Running on rpi4b, raspbian-ovos-dev image (w/o a TV connected to it) from April.
> 
> The skill loads, and throws an exception because the key isn't set. Expected that.
> 
> My settings.json is simple:
> 
> ```
> {
>     "key": "sk-xxxxxxxxx"
> }
> ```
> 
> The skill now loads silently indicating all is well but it remains silent forever with a fallthrough to the "Unknown" response.
> 
> The cause of the fallthrough is found in daemon.log: This skill imports the Persona libraries which throw:
> 
> `ModuleNotFoundError: No module named 'ovos_plugin_manager.templates.solvers'`
> 
> Upgrading ovos-plugin-manager doesn't eliminate the exception, but maybe I did that incorrectly?
> 

the OPM version this was introduced is [V0.0.23a13](https://github.com/OpenVoiceOS/ovos-plugin-manager/releases/tag/V0.0.23a13) , what version are you running? pip wont install alpha versions unless you explicitly request them

> I'm gonna roll my own gpt skill since the Persona stuff seems too elegant and fragile for my tastes. Establishing gpt personality is straight forward, and well documented, but I think it's too ephemeral/nuanced and fluid to constrain within a templated structure for now e.g., the number of "jailbreak" tricks being found.
> 
> I thought this should be reported because this will be a VERY popular skill on systems where it works.

Persona is a larger initiative than just ChatGPT, this skill is not using the persona code yet, when persona is done it will use the same solver plugin from error above and this skill will likely be archived/absorbed into persona

**Comment by ShuffleBit** [comment]
> the OPM version this was introduced is [V0.0.23a13](https://github.com/OpenVoiceOS/ovos-plugin-manager/releases/tag/V0.0.23a13) , what version are you running? pip wont install alpha versions unless you explicitly request them

There it is. I had 0.0.23a4, now 0.0.23a13. Thank you sir.
